import type { Metadata } from "next";
import { DataProvider } from "@/contexts/data";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import { User } from "@/interfaces/Idata";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUsers(): Promise<User[]> {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  if (!res.ok) {
    throw new Error("Failed to fetch users");
  }
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUsers = await getUsers();
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Sidebar />
        <DataProvider initialState={initialUsers}>{children}</DataProvider>
      </body>
    </html>
  );
}
