import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { DataProvider } from "@/contexts/data";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import { User } from "@/interfaces/Idata";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-primary",
});

async function getUsers(): Promise<User[]> {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  if (!res.ok) {
    throw new Error("Failed to fetch users");
  }
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUsers = await getUsers();
  return (
    <html lang="en">
      <body className={`antialiased ${spaceGrotesk.className} px-6 pt-7`}>
        <h1 className="page-heading">Dashboard</h1>
        <Sidebar />
        <main>
          <DataProvider initialState={initialUsers}>{children}</DataProvider>
        </main>
      </body>
    </html>
  );
}
